export const lowerCase = [
    {letter: 'a', disabled: false},
    {letter: 'b', disabled: false},
    {letter: 'c', disabled: false},
    {letter: 'd', disabled: false},
    {letter: 'e', disabled: false},
    {letter: 'f', disabled: false},
    {letter: 'g', disabled: false},
    {letter: 'h', disabled: false},
    {letter: 'i', disabled: false},
    {letter: 'j', disabled: false},
    {letter: 'k', disabled: false},
    {letter: 'l', disabled: false},
    {letter: 'm', disabled: false},
    {letter: 'n', disabled: false},
    {letter: 'o', disabled: false},
    {letter: 'p', disabled: false},
    {letter: 'q', disabled: false},
    {letter: 'r', disabled: false},
    {letter: 's', disabled: false},
    {letter: 't', disabled: false},
    {letter: 'u', disabled: false},
    {letter: 'v', disabled: false},
    {letter: 'w', disabled: false},
    {letter: 'x', disabled: false},
    {letter: 'y', disabled: false},
    {letter: 'z', disabled: false}
]

export const upperCase = [
    {letter: 'A', disabled: false},
    {letter: 'B', disabled: false},
    {letter: 'C', disabled: false},
    {letter: 'D', disabled: false},
    {letter: 'E', disabled: false},
    {letter: 'F', disabled: false},
    {letter: 'G', disabled: false},
    {letter: 'H', disabled: false},
    {letter: 'I', disabled: false},
    {letter: 'J', disabled: false},
    {letter: 'K', disabled: false},
    {letter: 'L', disabled: false},
    {letter: 'M', disabled: false},
    {letter: 'N', disabled: false},
    {letter: 'O', disabled: false},
    {letter: 'P', disabled: false},
    {letter: 'Q', disabled: false},
    {letter: 'R', disabled: false},
    {letter: 'S', disabled: false},
    {letter: 'T', disabled: false},
    {letter: 'U', disabled: false},
    {letter: 'V', disabled: false},
    {letter: 'W', disabled: false},
    {letter: 'X', disabled: false},
    {letter: 'Y', disabled: false},
    {letter: 'Z', disabled: false}
]
